spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.16.162:5432/familyTree
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  properties:
    hibernate.id.new_generator_mappings: true
    hibernate.cache.use_second_level_cache: true
    hibernate.cache.use_query_cache: false
    hibernate.generate_statistics: false
    hibernate.temp.use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:/data/changelog/db.changelog-master.xml
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  messages:
    basename: i18n/messages
#server:
#  ssl:
#    enabled: true
#    key-store: classpath:server.jks
#    key-store-password: 123456
#    key-password: 1234567
#    trust-store: classpath:server.jks
#    trust-store-password: 123456
#    client-auth: need
#    enabled-Protocols: [TLSv1.2]
---
spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.2:27017/familytree


